-- Run this in Supabase SQL Editor to add new tables

-- Add pack_sizes column to products table
alter table products add column if not exists amz_pack_size numeric default 1;
alter table products add column if not exists wmt_pack_size numeric default 1;
alter table products add column if not exists tgt_pack_size numeric default 1;
alter table products add column if not exists temu_pack_size numeric default 1;
alter table products add column if not exists other_pack_size numeric default 1;

-- Customer sales tracking table
create table if not exists customer_sales (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  customer_name text,
  customer_email text,
  customer_phone text,
  sale_date date default current_date,
  platform text default 'direct',
  notes text,
  total_singles numeric default 0
);

-- Customer sale line items
create table if not exists customer_sale_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  sale_id bigint references customer_sales(id) on delete cascade,
  product_id bigint references products(id),
  product_name text,
  root_sku text,
  pack_size numeric default 1,
  packs_ordered numeric default 0,
  singles_deducted numeric default 0,
  unit_price numeric default 0
);

-- Permanent notes/memory table
create table if not exists agent_notes (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  category text, -- 'customer', 'supplier', 'product', 'general'
  title text,
  content text
);

-- Packing list uploads tracking
create table if not exists packing_list_uploads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  supplier text,
  customer_name text,
  packing_list_number text,
  po_number text,
  direction text, -- 'inbound' or 'outbound'
  total_singles numeric default 0,
  raw_text text,
  processed boolean default false
);

-- Enable RLS
alter table customer_sales enable row level security;
alter table customer_sale_items enable row level security;
alter table agent_notes enable row level security;
alter table packing_list_uploads enable row level security;

-- Allow all for anon key
create policy "Allow all" on customer_sales for all using (true) with check (true);
create policy "Allow all" on customer_sale_items for all using (true) with check (true);
create policy "Allow all" on agent_notes for all using (true) with check (true);
create policy "Allow all" on packing_list_uploads for all using (true) with check (true);
