-- Run this entire script in Supabase SQL Editor

-- Products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  sku text,
  category text,
  stock numeric default 0,
  velocity numeric default 0,
  cost numeric default 0,
  price numeric default 0,
  reorder numeric default 0,
  supplier text,
  amz text,
  wmt text,
  tgt text,
  temu text,
  other_sku text
);

-- Orders log table
create table if not exists orders_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  platform text,
  order_sku text,
  product_id bigint references products(id),
  product_name text,
  qty_sold numeric,
  stock_before numeric,
  stock_after numeric
);

-- Change log table
create table if not exists change_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  description text,
  qty_change numeric,
  platform text
);

-- Uploaded files hash table (duplicate detection)
create table if not exists uploaded_files (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  file_hash text unique
);

-- Chat messages table
create table if not exists chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  role text not null,
  content text not null
);

-- Enable Row Level Security (open for now - single user app)
alter table products enable row level security;
alter table orders_log enable row level security;
alter table change_log enable row level security;
alter table uploaded_files enable row level security;
alter table chat_messages enable row level security;

-- Allow all operations for anon key (single-user app)
create policy "Allow all" on products for all using (true) with check (true);
create policy "Allow all" on orders_log for all using (true) with check (true);
create policy "Allow all" on change_log for all using (true) with check (true);
create policy "Allow all" on uploaded_files for all using (true) with check (true);
create policy "Allow all" on chat_messages for all using (true) with check (true);
